### ISSUE TITLE
error on vue2

### ISSUE THREAD

**Issue by xralphack** [Ginhing/vue-tagsinput#6]
Uncaught TypeError: _vm._h is not a function

**Comment by akatche** [comment]
Same here... on a fresh vuejs installation

**Comment by Ginhing** [comment]
Hello guys. Which version of vue do you use? The latest?

**Comment by xralphack** [comment]
latest

**Comment by Ginhing** [comment]
It was broken since the minor changes in [vue v2.1.7](https://github.com/vuejs/vue/releases/tag/v2.1.7). I have re-compiled the dist with latest vue now. You can have a try with  `vue-tagsinput@^2.0.1` 😄

**Comment by xralphack** [comment]
@Ginhing  works now
